[package]
name = "static_server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "static_server"

[lib]
doctest = false

[dependencies]
axum.workspace = true
axum-server.workspace = true
config = { workspace = true, features = ["toml"] }
etag.workspace = true
http.workspace = true
rustls.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["ansi", "env-filter"] }

http_utils = { path = "../lib/http_utils", features = ["server"] }
jwt.path = "../lib/jwt"
status_lists = { path = "../lib/status_lists", features = ["axum"] }
utils.path = "../lib/utils"
wallet_configuration.path = "../wallet/configuration"
