[package]
name = "wallet_provider_database_settings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[features]
test = ["config/toml", "dep:utils"]

[dependencies]
config = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true, features = ["chrono"] }
url = { workspace = true, features = ["serde"] }

utils = { path = "../../lib/utils", optional = true }
