[package]
name = "status_lists"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[[test]]
name = "postgres"
path = "tests/postgres.rs"
required-features = ["integration_test", "test"]

[[test]]
name = "revoke"
path = "tests/revoke.rs"
required-features = ["integration_test", "test"]

[[test]]
name = "router"
path = "tests/router.rs"
required-features = ["integration_test", "test"]

[features]
axum = ["dep:axum", "dep:etag", "dep:mediatype", "tower-http/compression-gzip"]
integration_test = ["axum", "dep:reqwest"]
test = ["dep:config"]

[dependencies]
anyhow.workspace = true
chrono.workspace = true
derive_more = { workspace = true, features = ["as_ref", "from", "into_iterator"] }
futures.workspace = true
itertools.workspace = true
nutype.workspace = true
rand.workspace = true
rstest.workspace = true
rustix = { workspace = true, features = ["fs"] }
sea-orm = { workspace = true, features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-postgres",
    "with-chrono",
    "with-uuid",
] }
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
url.workspace = true

axum = { workspace = true, optional = true }
config = { workspace = true, optional = true }
etag = { workspace = true, optional = true }
mediatype = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
tower-http = { workspace = true, optional = true }

attestation_types.path = "../../lib/attestation_types"
crypto.path = "../../lib/crypto"
jwt.path = "../../lib/jwt"
http_utils.path = "../../lib/http_utils"
hsm.path = "../../lib/hsm"
server_utils.path = "../server_utils"
token_status_list.path = "../../lib/token_status_list"
utils.path = "../../lib/utils"

[dev-dependencies]
anyhow.workspace = true
assert_matches.workspace = true
config.workspace = true
futures.workspace = true
p256.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "test-util"] }
uuid = { workspace = true, features = ["v4"] }

crypto = { path = "../../lib/crypto", features = ["generate", "mock"] }
server_utils = { path = "../server_utils", features = ["parsed_key_pair_conversion", "postgres", "test"] }
