[package]
name = "audit_log"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[[test]]
name = "macro"
path = "tests/macro.rs"
required-features = ["mock"]

[features]
mock = []
db_test = ["dep:db_test", "tokio/rt-multi-thread"]

[[test]]
name = "db_test"
path = "tests/db_test.rs"
required-features = ["db_test"]

[dependencies]
chrono.workspace = true
derive_more = { workspace = true, features = ["display"] }
sea-orm = { workspace = true, features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-postgres",
    "with-chrono",
    "with-json",
    "with-uuid",
] }
thiserror.workspace = true
tracing = { workspace = true, features = ["log"] }
uuid.workspace = true

audit_log_macros.path = "audit_log_macros"
utils.path = "../../lib/utils"

db_test = { path = "../../lib/db_test", optional = true }

[dev-dependencies]
assert_matches.workspace = true
config = { workspace = true, features = ["toml"] }
rstest.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["macros"] }
tracing-test.workspace = true
uuid = { workspace = true, features = ["v4"] }

utils = { path = "../../lib/utils", features = ["mock_time"] }
