apiVersion: v2
type: application
name: redis
version: 1.0.0
appVersion: "7.2"
description: A helm-chart for Redis.
dependencies:
  - name: sp-common
    repository: "file://../sp-common"
    version: 1.x.x
