[package]
name = "wallet_configuration"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
chrono = { workspace = true, features = ["serde"] }
derive_more = { workspace = true, features = ["debug"] }
itertools.workspace = true
rustls-pki-types.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true, features = ["base64"] }
thiserror.workspace = true
url = { workspace = true, features = ["serde"] }

attestation_data.path = "../../lib/attestation_data"
attestation_types.path = "../../lib/attestation_types"
crypto.path = "../../lib/crypto"
error_category.path = "../../lib/error_category"
http_utils = { path = "../../lib/http_utils", features = ["client"] }
jwt.path = "../../lib/jwt"
utils.path = "../../lib/utils"
