{{ $name := include "common.names.fullname" . }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{ if .Values.ingress.contextPath }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.maxBodySize | quote }}
{{ end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains"
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Content-Security-Policy: default-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'";
      more_set_headers "X-Permitted-Cross-Domain-Policies: none";
      more_set_headers "Cross-Origin-Resource-Policy: same-origin";
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "common.names.fullname" . }}
                port:
                  name: http
{{ if .Values.ingress.contextPath }}
            path: /{{ .Values.ingress.contextPath }}/(api/v1/(?:.*))
            pathType: ImplementationSpecific
{{ else }}
            path: /api/v1
            pathType: Prefix
{{ end }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.tlsSecretName | quote }}
{{ if .Values.ingressInternal.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}-internal
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.ingressInternal.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ingressInternal.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingressInternal.className }}
  rules:
    - host: {{ .Values.ingressInternal.hostname | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "common.names.fullname" . }}
                port:
                  name: http
            path: /admin
            pathType: Prefix
          - backend:
              service:
                name: {{ include "common.names.fullname" . }}
                port:
                  name: http
            path: /config
            pathType: Prefix
          - backend:
              service:
                name: {{ include "common.names.fullname" . }}
                port:
                  name: http
            path: /health
            pathType: Prefix
          - backend:
              service:
                name: {{ include "common.names.fullname" . }}
                port:
                  name: http
            path: /openapi.json
            pathType: Prefix
          - backend:
              service:
                name: {{ include "common.names.fullname" . }}
                port:
                  name: http
            path: /api-docs
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.ingressInternal.hostname | quote }}
      secretName: {{ .Values.ingressInternal.tlsSecretName | quote }}
{{ end }}
