apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}
  {{- with .Values.extraAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
spec:
  serviceName: {{ include "common.names.fullname" . | quote}}
  replicas: 1
  selector:
    matchLabels:
    {{- include "common.labels.componentSelectorLabels" (list "server" .) | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "common.labels.componentSelectorLabels" (list "server" .) | nindent 8 }}
      {{- with .Values.extraPodLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "common.names.fullname" . }}
        image: {{ printf "%s:%s" (list .Values.global.imageRegistry .Values.image.repository | compact | join "/") .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /usr/local/bin/redis-server
        - --port
        - {{ .Values.redis.server.port | quote }}
        - --loglevel
        - {{ .Values.redis.server.logLevel | quote }}
        - --appendonly
        - {{ .Values.redis.server.appendOnly | quote }}
        - --save
        - {{ .Values.redis.server.save | quote }}
        {{- if .Values.redis.server.initialKeys }}
        lifecycle:
          postStart:
            exec:
              command:
              - /usr/local/bin/redis-cli
              - mset
              {{- range $key, $value := .Values.redis.server.initialKeys }}
              - {{ $key | quote }}
              - {{ $value | quote }}
              {{- end }}
        {{- end }}
        resources:
        {{- toYaml .Values.resources | nindent 12 }}
        ports:
        - name: redis
          containerPort: {{ .Values.redis.server.port }}
  {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
      {{- with .Values.extraAnnotations }}
      annotations:
      {{- toYaml . | nindent 10 }}
      {{- end }}
      labels:
      {{- include "common.labels.standard" . | nindent 10 }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      {{- if .Values.persistence.storageClassName }}
      storageClassName: {{ .Values.persistence.storageClassName }}
      {{- end }}
  {{- end }}
