[[IgnoredVulns]]
id = "RUSTSEC-2023-0071"
ignoreUntil = 2026-07-01
reason = "The vulnerability pertains to the use of RSA private keys in the rsa crate. We only use this crate to evaluate RSA public keys as found in Google CA certificates."

[[IgnoredVulns]]
id = "RUSTSEC-2024-0436"
ignoreUntil = 2026-07-01
reason = "This is a transitive dependency that is no longer maintained but used by a couple dependencies. Waiting for dependencies to find alternatives."

[[IgnoredVulns]]
id = "RUSTSEC-2025-0141"
ignoreUntil = 2026-07-01
reason = "`bincode` is a transitive dependency that is no longer maintained but considered complete and used by `http-cache`. Waiting for `http-cache` to find alternatives."

[[IgnoredVulns]]
id = "GHSA-33mh-2634-fwr2"
ignoreUntil = 2026-07-01
reason = "We are not vulnerable as there are no user controlled URI paths."

[[IgnoredVulns]]
id = "GHSA-2g4f-4pwh-qvx6"
ignoreUntil = 2026-07-01
reason = "We are not vulnerable as ajv is only run as dev-dependency. Also eslint pinned their dependency on 6.x.y. and will not update. See https://github.com/eslint/eslint/pull/19340."

[[IgnoredVulns]]
id = "RUSTSEC-2025-0134"
ignoreUntil = 2026-07-01
reason = "This is a transitive dependency that is no longer maintained. Waiting for testcontainers_modules to update to new testcontainers version in which it should be fixed."
