apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  {{- with .Values.extraAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
    {{- include "common.labels.componentSelectorLabels" (list "server" .) | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "common.labels.componentSelectorLabels" (list "server" .) | nindent 8 }}
      {{- with .Values.extraPodLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "common.names.fullname" . }}
        image: {{ printf "%s:%s" (list .Values.global.imageRegistry .Values.image.repository | compact | join "/") .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
        {{- toYaml .Values.resources | nindent 12 }}
        ports:
        - name: max
          containerPort: {{ .Values.max.config.asgi.port }}
        volumeMounts:
        - mountPath: {{ .Values.max.home }}/max.conf
          name: files
          subPath: max.conf
          readOnly: true
        - mountPath: {{ .Values.max.home }}/resources/js/mock_redirect.js
          name: files
          subPath: mock_redirect.js
          readOnly: true
        - mountPath: {{ .Values.max.home }}/static/assets/mock_redirect-ncEe772z.js
          name: files
          subPath: mock_redirect.js
          readOnly: true
        - mountPath: {{ .Values.max.home }}/config/clients.json
          name: files
          subPath: clients.json
          readOnly: true
        - mountPath: {{ .Values.max.home }}/config/login_methods.json
          name: files
          subPath: login_methods.json
          readOnly: true
        - mountPath: {{ .Values.max.home }}/secrets/clients/test_client/test_client.crt
          name: files
          subPath: test_client.crt
          readOnly: true
        - mountPath: {{ .Values.max.home }}/saml/digid/PrivateRootCA-G1.pem
          name: files
          subPath: PrivateRootCA-G1.pem
          readOnly: true
        - mountPath: {{ .Values.max.home }}/saml/digid/settings.json
          name: files
          subPath: saml-digid-preprod-settings.json
          readOnly: true
        - mountPath: {{ .Values.max.home }}/saml/digid/metadata/idp_metadata.xml
          name: files
          subPath: saml-digid-preprod-idp-metadata.xml
          readOnly: true
        - mountPath: {{ .Values.max.home }}/saml/templates/xml/sp_metadata.xml.jinja
          name: files
          subPath: saml-sp-metadata-template.xml.jinja
          readOnly: true
        - mountPath: {{ .Values.max.home }}/saml/digid/certs/sp.key
          name: secrets
          subPath: {{ .Values.max.secret.privateKeyName }}
          readOnly: true
        - mountPath: {{ .Values.max.home }}/saml/digid/certs/sp.crt
          name: secrets
          subPath: {{ .Values.max.secret.certificateName }}
          readOnly: true
        - mountPath: {{ .Values.max.home }}/secrets/oidc/jwks-certs/jwe_sign.crt
          name: secrets
          subPath: {{ .Values.max.secret.certificateName }}
          readOnly: true
      volumes:
      - name: files
        configMap:
          name: {{ include "common.names.fullname" . }}-files
      - name: secrets
        secret:
          secretName: {{ .Values.max.secret.secretName }}
