name: Build the app

on:
  - push
  - pull_request
    
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/nl-wallet-showcase-builder-android-flutter:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3

      - name: Run Flutter doctor
        run: flutter doctor

      - name: Run tests
        run: flutter test


  build-and-distribute-release:
    if: ${{ startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'beta/') || startsWith(github.ref_name, 'alpha/') }}

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/nl-wallet-showcase-builder-android-flutter:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      ANDROID_PACKAGE_NAME: nl.rijksoverheid.edi.wallet
      FDROID_DEPLOY_REPO: nl-wallet-showcase-fdroid
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3

      - name: Build a release with overriden package name, version name and version code
        run: ./.github/workflows/build_release.sh

      - name: Upload release APK as artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # pin@v3
        with:
          name: ${{ env.APK_NAME }}
          path: build/app/outputs/apk/release
          if-no-files-found: error

      - uses: webfactory/ssh-agent@fc49353b67b2b7c1e0e6a600572d01a69f2672dd # pin@v0.5.4
        with:
          ssh-private-key: ${{ secrets.FDROID_DEPLOY_KEY }}

      - name: Publish unsigned release to F-Droid git repository
        run: ./.github/workflows/publish_release.sh
